name: CI

on: 
  push:
    branches:
      - main

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile and Deploy LaTeX to PDF
      uses: raven38/uberblatt-action@v11
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: "build/"
        GH_PAT: ${{ secrets.GH_PAT }}
